name: Build and test SwiftPango

# Dependencies of this package
env:
  UBUNTU_APT: ${{ 'libpango1.0-dev gir1.2-pango-1.0 libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq' }}

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  # macOS tasks
  build-mac-swift-latest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.2'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout SwiftPango
        uses: actions/checkout@v2
        with:
          path: SwiftPango

      - name: Build Swift Wrappers
        run: |
          cd SwiftPango
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftPango
        run: |
          cd SwiftPango
          swift build `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Test SwiftPango
        run: |
          cd SwiftPango
          swift test `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd SwiftPango
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-macos
          path: |
            SwiftPango/
          retention-days: 1

  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version
      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftPango
        uses: actions/checkout@v2
        with:
          path: SwiftPango

      - name: Build current SwiftPango
        run: |
          cd SwiftPango
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftPango
        run: |
          cd SwiftPango
          swift build
          cd ..

      - name: Test SwiftPango
        run: |
          cd SwiftPango
          swift test
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd SwiftPango
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-20.04-5.3
          path: |
            SwiftPango/
          retention-days: 1

  # Ubuntu 18.04 tasks
  build-ubuntu-18_04-swift-latest:
    runs-on: ubuntu-18.04
    steps:
      - name: Print Swift version to confirm
        run: swift --version
      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftPango
        uses: actions/checkout@v2
        with:
          path: SwiftPango

      - name: Build current SwiftPango
        run: |
          cd SwiftPango
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftPango
        run: |
          cd SwiftPango
          swift build
          cd ..

      - name: Test SwiftPango
        run: |
          cd SwiftPango
          swift test
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: |
          cd SwiftPango
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-18.04-5.3
          path: |
            SwiftPango/
          retention-days: 1
